// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Jugador":return img`
........................
........................
........fffffff.........
.......fffffffff........
.......faaafaaaf........
.......faaafaaaf........
.......faaafaaaf........
.......faaafaaaf........
.......faaafaaaf........
.......fffffffff........
........fffffff.........
........fffffff.........
.......fffffffff........
.......fffffffff........
.......ffffaffff........
.......fffaaafff........
.......ffffaffff........
.......fffffffff........
.......fffffffff........
.......fffffffff........
.......fffffffff........
.......fffffffff........
........fffffff.........
........fffffff.........
........fff.fff.........
........fff.fff.........
........fff.fff.........
........fff.fff.........
........fff.fff.........
........fff.fff.........
........fff.fff.........
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("json", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
